test_that("show brain LUT", {
    dl <-  matrix(0,3,4)
    cm <-  matrix(c(1,2,1,1),2)
    expect_equal(show.brain.lut(lut = dl, cl =cm), dl)
    expect_equal(show.brain.lut(lut = dl, cl =cm, test = TRUE), "direct lut")
    expect_equal(show.brain.lut(lut = t(dl), cl =cm), dl)
    expect_equal(show.brain.lut(lut = t(dl), cl =cm, test = TRUE), "t(lut)")
    expect_error(show.brain.lut(lut = matrix(0,2,2), cl =cm), "wrong LUT format")
    expect_error(show.brain.lut(lut = pi, cl =cm), "unknown type of lut")
    expect_error(show.brain.lut(lut = "mylut.lut", cl =cm), "cannot find file")
    expect_error(show.brain.lut(10, "/usr", cl =cm), "no matching file")
})
