# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' write LUT
#' 
#' Write RGB color lookup table (LUT) of 3\eqn{\times}{x}256 bytes. 
#' Implemented with Rcpp to allow writing bytes.
#' 
#' @name writelut
#' @param x vector of 768 bytes (treated as unsigned integer)
#' @param filename name for output file
#' 
#' @return 0 on success
#' @export
writelut <- function(x, filename) {
    .Call('_clusterLUTs_writelut', PACKAGE = 'clusterLUTs', x, filename)
}

